spring:
  application:
    name: oauth2
  cloud:
    config:
      name: oauth2
      discovery:
        service-id: oauth2
        enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
    #    password: Adgjl!2345
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: false
        generate_statistics: false
        use-new-id-generator-mappings: false

learn:
  security:
    jwt:
      signkey: BNP5PoFaq12UapkBymWQDbhniFr65lWG

server:
  port: 8089
  servlet:

eureka:
  #  instance:
  #    leaseRenewalIntervalInSeconds: 5
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#    region: default
#    registryFetchIntervalSeconds: 5

#ribbon:
#  ReadTimeout: 60000
#  ConnectTimeout: 60000
#  MaxAutoRetries: 1
#  MaxAutoRetriesNextServer: 2
#  eureka:
#    enabled: true
#hystrix:
#  command:
#    default:
#      execution:
#        timeout:
#          enabled: true
#        isolation:
#          thread:
#            timeoutInMilliseconds: 720000

logging:
  file: logs/oauth2-log.txt
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  level:
    com.eiz.ecosys.account: DEBUG
    org.springframework: DEBUG
    org.hibernate: DEBUG
