spring:
  application:
    name: eureka
  cloud:
    config:
      name: eureka
      discovery:
        service-id: eureka
        enabled: true

server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/